;; lazy streams as (value . thunk): take/map/filter over infinite
;; streams, plus the sieve of Eratosthenes
(define (s-cons v th) (cons v th))
(define (s-head s) (car s))
(define (s-tail s) ((cdr s)))
(define (nats-from n) (s-cons n (lambda () (nats-from (+ n 1)))))
(define (s-take s n)
  (if (eq? n 0) '() (cons (s-head s) (s-take (s-tail s) (- n 1)))))
(define (s-map f s) (s-cons (f (s-head s)) (lambda () (s-map f (s-tail s)))))
(define (s-filter p s)
  (if (p (s-head s))
      (s-cons (s-head s) (lambda () (s-filter p (s-tail s))))
      (s-filter p (s-tail s))))
(define (sieve s)
  (let ([p (s-head s)])
    (s-cons p (lambda ()
                (sieve (s-filter (lambda (n) (not (eq? (remainder n p) 0)))
                                 (s-tail s)))))))
(println (s-take (nats-from 0) 8))
(println (s-take (s-map (lambda (n) (* n n)) (nats-from 1)) 8))
(println (s-take (sieve (nats-from 2)) 15))
;; fibs as a self-referential-ish stream (zip of two shifted streams)
(define (s-zip+ a b)
  (s-cons (+ (s-head a) (s-head b)) (lambda () (s-zip+ (s-tail a) (s-tail b)))))
(define (fibs)
  (s-cons 0 (lambda () (s-cons 1 (lambda () (s-zip+ (fibs) (s-tail (fibs))))))))
(println (s-take (fibs) 12))
(s-head (s-filter (lambda (n) (< 100 n)) (sieve (nats-from 2))))
