;; prelude exercises
(println (map (lambda (x) (* x x)) (range 0 6)))
(println (filter even? (range 0 10)))
(println (foldl + 0 (range 1 101)))
(println (foldr cons '() (list 1 2 3)))
(println (reverse (list 'a 'b 'c)))
(println (append (list 1 2) (list 3 4)))
(println (list (length (range 0 42)) (list-ref (range 0 10) 3)))
(println (member 3 (list 1 2 3 4)))
(println (assoc 'b (list (cons 'a 1) (cons 'b 2))))
(println (list (max 3 9) (min 3 9) (abs -7) (add1 41) (zero? 0)))
(println (list->vector (list 1 2 3)))
(println (vector->list (vector 'x 'y)))
(println (list (andmap even? (list 2 4)) (ormap odd? (list 2 4)) (list? (list 1)) (list? 5)))
(last (list 1 2 3))
