;; the bootstrap feature batch, end to end
(define g1 (gensym 'tmp))
(define g2 (gensym 'tmp))
(println (list (symbol? g1) (eq? g1 g2)))                       ;; (#t #f)
(println (value->string (list 1 'two (vector 3) "four")))             ;; (1 two #(3) four)
(println (format "~a + ~a = ~a~%done~~" (list 1 2 (+ 1 2))))
(println (substring "hello world" 6 11))                        ;; world
(println (list (string<? "apple" "banana") (string<? "b" "a")))
(println (string-byte "A" 0))                                   ;; 65
(println (number->string -42))
(println (list (string->number "123") (string->number "12x")))
(println (list (bitwise-and 12 10) (bitwise-ior 12 10) (bitwise-xor 12 10)))
(println (list (arithmetic-shift 3 4) (arithmetic-shift 48 -4)))
(println (list (modulo 7 3) (modulo -7 3) (remainder -7 3)))
(println (sort (list 5 3 9 1 3) <))
(println (sort (list 'cherry 'apple 'banana) symbol<?))
(println (apply + (list 1 2)))
(println (map2 cons (list 1 2 3) (list 'a 'b 'c)))
(println (string-join (list "a" "b" "c") ", "))
(println (list (take (range 0 9) 3) (drop (range 0 9) 6)))
(println (list (index-of '(a b c) 'c) (index-of '(a b) 'z)))
(println (append-map (lambda (x) (list x x)) '(1 2)))
(println (filter-map (lambda (x) (if (even? x) (* x 10) #f)) (range 0 6)))
(println (list (findf odd? '(2 4 5 6)) (car (partition even? (range 0 6)))))
(println (sort (set->list (set-intersect (set 1 2 3 4) (list->set '(2 4 6)))) <))
(println (set-count (set-union (set 1 2) (set 2 3))))
(println (set-count (set-subtract (set 1 2 3) (set 2))))
(displayln 'done)
'ok
