;; read + sets/hashes interplay, symbols as keys
(define seen (make-set))
(define counts (make-hash))
(define (tally k)
  (begin (set-add! seen k)
         (hash-set! counts k (+ 1 (hash-ref/default counts k 0)))))
(let loop ([i 0])
  (when (< i 10)
    (tally (remainder (read) 3))
    (loop (+ i 1))))
(println (set-count seen))
(println (hash-ref/default counts 0 0))
(display (hash-count counts)) (newline)
(- (set-count seen) (hash-count counts))
