;;; puffin-mode.el --- Major mode for the Puffin language -*- lexical-binding: t; -*-

;; Author: Puffin project
;; Keywords: languages, lisp
;; Package-Requires: ((emacs "28.1"))
;; Version: 0.1

;;; Commentary:

;; A major mode for Puffin (.puf), the s-expression Scheme dialect
;; compiled by the reference compiler in src/.  Provides font-lock,
;; scheme-style indentation, compile/run and interpret commands, an
;; inferior REPL over bin/puffin, and eglot integration with
;; bin/puffin-lsp.
;;
;; See README.md in this directory for an install snippet.

;;; Code:

(require 'comint)
(require 'scheme)  ;; for `scheme-indent-function' and its properties

;; ---------------------------------------------------------------------
;; Repo / tool discovery
;; ---------------------------------------------------------------------

(defun puffin--repo-root ()
  "The puffin-lang repo root dominating the current buffer, or nil."
  (let ((dir (or (and buffer-file-name (file-name-directory buffer-file-name))
                 default-directory)))
    (locate-dominating-file dir "bin/puffin-lsp")))

(defun puffin--bin (name)
  "Absolute path of bin/NAME in the dominating repo, else NAME from PATH."
  (let ((root (puffin--repo-root)))
    (if root
        (expand-file-name (concat "bin/" name) root)
      name)))

;; ---------------------------------------------------------------------
;; Font-lock
;; ---------------------------------------------------------------------

(defconst puffin-keywords
  '("define" "lambda" "λ" "match" "let" "let*" "letrec" "if" "cond"
    "case" "when" "unless" "begin" "set!" "quote" "quasiquote"
    "unquote" "unquote-splicing" "while" "module" "provide" "require"
    "signature")
  "Puffin special forms and structural keywords.")

;; generated by tools/lsp/gen-el-keywords.rkt -- do not edit by hand
(defconst puffin-stdlib-builtins
  '("arithmetic-shift" "bitwise-and" "bitwise-ior" "bitwise-xor" "boolean?"
    "car" "cdr" "command-line-args" "cons" "display"
    "equal?" "error" "file-exists?" "fixnum?" "gensym"
    "hash" "hash-count" "hash-has-key?" "hash-keys" "hash-ref"
    "hash-ref/default" "hash-remove" "hash-remove!" "hash-set" "hash-set!"
    "hash?" "make-hash" "make-set" "make-vector" "modulo"
    "newline" "null?" "number->string" "pair?" "println"
    "procedure?" "quotient" "read" "read-all" "read-file"
    "remainder" "set" "set->list" "set-add" "set-add!"
    "set-count" "set-member?" "set-remove" "set-remove!" "set?"
    "string->number" "string->symbol" "string-append" "string-byte" "string-length"
    "string<?" "string=?" "string?" "substring" "symbol->string"
    "symbol?" "system" "value->string" "vector-length" "vector-ref"
    "vector-set!" "vector?" "void?" "write-file")
  "Surface stdlib primitives from src/stdlib.rkt.")
;; end generated section

(defconst puffin-font-lock-keywords
  `(;; (define (name ...) / (define name ...)
    ("(define\\s-+(?\\(\\(?:\\sw\\|\\s_\\)+\\)"
     (1 font-lock-function-name-face))
    ;; special forms
    (,(regexp-opt puffin-keywords 'symbols) . font-lock-keyword-face)
    ;; stdlib primitives
    (,(regexp-opt puffin-stdlib-builtins 'symbols) . font-lock-builtin-face)
    ;; #t / #f
    ("#[tf]\\_>" . font-lock-constant-face)
    ;; quoted symbols
    ("'\\(\\(?:\\sw\\|\\s_\\)+\\)" (1 font-lock-constant-face)))
  "Font-lock rules for `puffin-mode'.")

;; ---------------------------------------------------------------------
;; Indentation: scheme-style, driven by `scheme-indent-function'.
;; ---------------------------------------------------------------------

;; scheme.el already sets properties for define/lambda/let/letrec/
;; when/unless/case/do; add Puffin's own forms.  `match' clauses
;; indent like cond clauses (one distinguished argument).
(put 'define 'scheme-indent-function 1)
(put 'lambda 'scheme-indent-function 1)
(put 'λ 'scheme-indent-function 1)
(put 'match 'scheme-indent-function 1)
(put 'let 'scheme-indent-function 'scheme-let-indent)
(put 'when 'scheme-indent-function 1)
(put 'unless 'scheme-indent-function 1)
(put 'while 'scheme-indent-function 1)
(put 'module 'scheme-indent-function 2)

;; ---------------------------------------------------------------------
;; Run / interpret commands
;; ---------------------------------------------------------------------

(defun puffin--buffer-file ()
  "Save and return the current buffer's file, erroring if none."
  (unless buffer-file-name
    (user-error "Buffer is not visiting a file"))
  (save-buffer)
  buffer-file-name)

(defun puffin-run-buffer ()
  "Compile and run the current file with bin/puffin (native)."
  (interactive)
  (let ((file (puffin--buffer-file)))
    (compile (format "%s %s"
                     (shell-quote-argument (puffin--bin "puffin"))
                     (shell-quote-argument file)))))

(defun puffin-interp-buffer ()
  "Interpret the current file with bin/puffin -i (fast startup)."
  (interactive)
  (let ((file (puffin--buffer-file)))
    (compile (format "%s -i %s"
                     (shell-quote-argument (puffin--bin "puffin"))
                     (shell-quote-argument file)))))

;; ---------------------------------------------------------------------
;; Inferior REPL (bin/puffin with no file is the REPL)
;; ---------------------------------------------------------------------

(defvar puffin-repl-buffer-name "*puffin*"
  "Name of the inferior Puffin REPL buffer.")

;;;###autoload
(defun run-puffin ()
  "Start (or switch to) an inferior Puffin REPL."
  (interactive)
  (let ((buf (get-buffer puffin-repl-buffer-name)))
    (unless (and buf (comint-check-proc buf))
      (setq buf (make-comint "puffin" (puffin--bin "puffin"))))
    (pop-to-buffer buf)))

(defun puffin--repl-process ()
  "The running REPL process, starting one if needed."
  (unless (comint-check-proc puffin-repl-buffer-name)
    (save-window-excursion (run-puffin)))
  (get-buffer-process puffin-repl-buffer-name))

(defun puffin-send-region (start end)
  "Send the region between START and END to the Puffin REPL."
  (interactive "r")
  (let ((proc (puffin--repl-process))
        (text (string-trim (buffer-substring-no-properties start end))))
    (comint-send-string proc (concat text "\n"))
    (display-buffer puffin-repl-buffer-name)))

(defun puffin-send-definition ()
  "Send the top-level form around point to the Puffin REPL."
  (interactive)
  (save-excursion
    (end-of-defun)
    (let ((end (point)))
      (beginning-of-defun)
      (puffin-send-region (point) end))))

;; ---------------------------------------------------------------------
;; Eglot integration
;; ---------------------------------------------------------------------

(defvar eglot-server-programs) ;; loaded with eglot; declared to quiet the byte-compiler

(defun puffin-eglot-setup ()
  "Register bin/puffin-lsp with eglot for `puffin-mode'.
Finds the repo root by `locate-dominating-file' for bin/puffin-lsp,
so it works from any buffer inside the puffin-lang checkout.  Call
it from `puffin-mode-hook' (or once, from your init file, with a
puffin buffer current)."
  (let ((root (puffin--repo-root)))
    (when root
      (with-eval-after-load 'eglot
        (add-to-list 'eglot-server-programs
                     `(puffin-mode
                       . (,(expand-file-name "bin/puffin-lsp" root))))))))

;; ---------------------------------------------------------------------
;; The mode
;; ---------------------------------------------------------------------

(defvar puffin-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-c C-c") #'puffin-run-buffer)
    (define-key map (kbd "C-c C-i") #'puffin-interp-buffer)
    (define-key map (kbd "C-c C-z") #'run-puffin)
    (define-key map (kbd "C-c C-r") #'puffin-send-region)
    (define-key map (kbd "C-M-x")   #'puffin-send-definition)
    map)
  "Keymap for `puffin-mode'.")

;;;###autoload
(define-derived-mode puffin-mode lisp-data-mode "Puffin"
  "Major mode for editing Puffin programs.

\\{puffin-mode-map}"
  ;; # begins #t/#f (and future #-syntax): a symbol constituent
  (modify-syntax-entry ?# "_" puffin-mode-syntax-table)
  ;; brackets are parens, as in Racket
  (modify-syntax-entry ?\[ "(]" puffin-mode-syntax-table)
  (modify-syntax-entry ?\] ")[" puffin-mode-syntax-table)
  (setq-local font-lock-defaults '(puffin-font-lock-keywords))
  (setq-local lisp-indent-function #'scheme-indent-function)
  (setq-local comment-start ";")
  (setq-local comment-add 1)
  (puffin-eglot-setup))

;;;###autoload
(add-to-list 'auto-mode-alist '("\\.puf\\'" . puffin-mode))

(provide 'puffin-mode)

;;; puffin-mode.el ends here
