(program
  (let ([r (read)])
    (let ([s (read)])
      (let ([d (- r s)])                    
        (if (and (> r 0) (or (<= d 0) (>= s 0)))
            (if (not (eq? r s))
                (+ (+ r s) (- d))           
                (- (+ r s) d))              
            (if (< r s)
                (+ (- r 1) (+ s 1))         
                (+ 0 0)))))))
