#lang racket

;; Puffin -- tools/lsp/gen-el-keywords.rkt: print the elisp defconst
;; of surface stdlib primitive names, for pasting into
;; editor/emacs/puffin-mode.el (its generated section). Run:
;;
;;   racket tools/lsp/gen-el-keywords.rkt
;;
;; The manifest (src/stdlib.rkt) is the single source of truth; rerun
;; this and re-paste whenever primitives are added.

(require (only-in "../../src/stdlib.rkt"
                  stdlib-primitives prim-spec-name prim-spec-surface?))

(define names
  (sort (for/list ([s stdlib-primitives] #:when (prim-spec-surface? s))
          (symbol->string (prim-spec-name s)))
        string<?))

(printf ";; generated by tools/lsp/gen-el-keywords.rkt -- do not edit by hand\n")
(printf "(defconst puffin-stdlib-builtins\n")
(printf "  '(")
(for ([n names] [i (in-naturals)])
  (when (positive? i)
    (if (zero? (modulo i 5)) (printf "\n    ") (printf " ")))
  (printf "~s" n))
(printf ")\n")
(printf "  \"Surface stdlib primitives from src/stdlib.rkt.\")\n")
