#lang racket
;; Generate web/src/engine/prim-names.js from the stdlib manifest —
;; the surface-primitive name list Monaco uses for autocomplete and
;; highlighting. Derives from src/stdlib.rkt (the single source of
;; truth for prims) so the editor never drifts from the language.
;; Regenerate after editing the manifest:
;;   racket tools/gen-prim-names.rkt
(require "../src/stdlib.rkt")

(define names
  (for/list ([s stdlib-primitives] #:when (prim-spec-surface? s))
    (symbol->string (prim-spec-name s))))

(define out (build-path (current-directory) "web" "src" "engine" "prim-names.js"))
(call-with-output-file out #:exists 'replace
  (lambda (p)
    (fprintf p "// GENERATED by tools/gen-prim-names.rkt from src/stdlib.rkt — do not edit.\n")
    (fprintf p "// Surface primitive names, for the editor (autocomplete/highlight).\n")
    (fprintf p "export function surfacePrimNames() {\n  return [\n")
    (for ([n (sort names string<?)])
      (fprintf p "    ~s,\n" n))
    (fprintf p "  ];\n}\n")))
(printf "wrote ~a\n" out)
