#lang racket

;; Puffin -- gen-puffincc-tables.rkt: generate the data files that
;; keep puffincc (the compiler written in Puffin) in lockstep with
;; the Racket reference:
;;
;;   racket src/gen-puffincc-tables.rkt
;;
;; writes puffincc-src/tables.puf (the primitive manifest as
;; Puffin data) and puffincc-src/prelude-data.puf (the prelude's
;; forms as quoted data, for puffincc's own prelude injection).
;; Regenerate after editing stdlib.rkt or prelude.puf.

(require racket/runtime-path)
(require "stdlib.rkt")

(define-runtime-path here ".")
(define out-dir (build-path here 'up "puffincc-src"))
(make-directory* out-dir)

(with-output-to-file (build-path out-dir "tables.puf") #:exists 'replace
  (λ ()
    (displayln ";; GENERATED by src/gen-puffincc-tables.rkt from src/stdlib.rkt.")
    (displayln ";; Do not edit: regenerate instead.")
    (newline)
    (displayln ";; (name arity rt-sym surface?)")
    (printf "(define prim-table\n  '~s)\n\n"
            (for/list ([s stdlib-primitives])
              (list (prim-spec-name s) (prim-spec-arity s)
                    (prim-spec-rt-sym s) (prim-spec-surface? s))))
    (displayln "(define prim-hash")
    (displayln "  (foldl (lambda (row acc) (hash-set acc (car row) (cdr row))) (hash) prim-table))")
    (newline)
    (displayln "(define (stdlib-prim? op) (hash-has-key? prim-hash op))")
    (displayln "(define (stdlib-arity op) (first (hash-ref prim-hash op)))")
    (displayln "(define (stdlib-rt-sym op) (second (hash-ref prim-hash op)))")
    (displayln "(define (surface-stdlib-prim? op)")
    (displayln "  (and (hash-has-key? prim-hash op) (third (hash-ref prim-hash op))))")))

(with-output-to-file (build-path out-dir "prelude-data.puf") #:exists 'replace
  (λ ()
    (displayln ";; GENERATED by src/gen-puffincc-tables.rkt from src/prelude.puf.")
    (displayln ";; The prelude's forms as data, for puffincc's prelude injection.")
    (newline)
    (define forms
      (with-input-from-file (build-path here "prelude.puf")
        (λ () (let loop ([acc '()])
                (define f (read))
                (if (eof-object? f) (reverse acc) (loop (cons f acc)))))))
    (printf "(define prelude-forms-data\n  '~s)\n" forms)))

(displayln "wrote puffincc-src/tables.puf and prelude-data.puf")
