#lang racket

;; Puffin -- test.rkt: the golden test runner.
;;
;; Corpus: every program in test-programs/ (all of the class
;; projects' example programs, r0-* through r5-*, plus the new
;; puffin-* feature tests), each run against every input file in
;; input-files/.
;;
;; Goldens are generated by the *reference interpreter* (desugar +
;; interpret-puffin, whose behavior comes from the stdlib manifest),
;; and every other execution route must agree byte-for-byte:
;;
;;   racket test.rkt gen                  regenerate goldens/
;;   racket test.rkt -m interp            reference interpreter
;;   racket test.rkt -m chain             every pass's interpreter agrees
;;                                        + all IR predicates hold (slow)
;;   racket test.rkt -m x86-64            compile + run native (Rosetta on ARM macs)
;;   racket test.rkt -m arm64             compile + run native
;;   racket test.rkt -m all               interp + both native targets
;;   racket test.rkt ... r3-4 puffin-1    restrict to named programs
;;
;; Exit status: 0 iff everything passed.

(require racket/runtime-path)
(require "system.rkt")
(require "irs.rkt")
(require "compile.rkt")
(require "interpreters.rkt")
(require "main.rkt")

(define-runtime-path here ".")
(define tests-dir  (build-path here "test-programs"))
(define inputs-dir (build-path here "input-files"))
(define goldens-dir (build-path here "goldens"))

(define mode (make-parameter "all"))

(define (program-names)
  (sort (for/list ([f (directory-list tests-dir)]
                   #:when (regexp-match? #rx"\\.(scm|puf)$" (path->string f)))
          (path->string (path-replace-extension f "")))
        string<?))

(define (input-names)
  (sort (map (λ (p) (path->string (path-replace-extension p ""))) (directory-list inputs-dir)) string<?))

(define (program-path name)
  (define scm (build-path tests-dir (string-append name ".scm")))
  (if (file-exists? scm) scm (build-path tests-dir (string-append name ".puf"))))

(define (input-ints input-name)
  (map string->number
       (filter (λ (s) (not (string=? s "")))
               (regexp-split #px"\\s+" (file->string (build-path inputs-dir (string-append input-name ".in")))))))

(define (golden-path prog input) (build-path goldens-dir (format "~a_~a.golden" prog input)))

;; ---------------------------------------------------------------------
;; The reference execution: desugar + interpret, capturing output.
;; Returns (ok . stdout-string) or (error . message).
;; ---------------------------------------------------------------------

(define (reference-output prog input)
  (define p (read-program-file (program-path prog)))
  (with-handlers ([exn:fail? (λ (e) (cons 'error (exn-message e)))])
    (match (run/capture (λ () (interpret-puffin (desugar p) (input-ints input))))
      [(cons _ out) (cons 'ok out)])))

;; ---------------------------------------------------------------------
;; gen: write goldens (skipping programs the reference itself rejects,
;; with a loud note--those need attention, not silence)
;; ---------------------------------------------------------------------

(define (generate-goldens progs)
  (make-directory* goldens-dir)
  (define skipped '())
  (for ([prog progs])
    (for ([input (input-names)])
      (match (reference-output prog input)
        [(cons 'ok out)
         (with-output-to-file (golden-path prog input)
           (λ () (display out)) #:exists 'replace)]
        [(cons 'error msg)
         (set! skipped (cons (list prog input msg) skipped))])))
  (displayln (format "goldens written for ~a programs x ~a inputs"
                     (length progs) (length (input-names))))
  (for ([s (reverse skipped)])
    (displayln (format "!! no golden (reference error): ~a/~a: ~a" (first s) (second s)
                       (let ([m (third s)]) (substring m 0 (min 100 (string-length m))))))))

;; ---------------------------------------------------------------------
;; checking helpers
;; ---------------------------------------------------------------------

(define failures (box '()))
(define n-checks (box 0))

(define (check! what prog input got expected)
  (set-box! n-checks (add1 (unbox n-checks)))
  (unless (equal? (string-trim got) (string-trim expected))
    (set-box! failures (cons (list what prog input got expected) (unbox failures)))
    (displayln (format "FAIL [~a] ~a/~a\n  expected: ~s\n  got:      ~s"
                       what prog input (string-trim expected) (string-trim got)))))

(define (golden-for prog input)
  (define gp (golden-path prog input))
  (and (file-exists? gp) (file->string gp)))

;; ---------------------------------------------------------------------
;; interp mode
;; ---------------------------------------------------------------------

(define (run-interp-tests progs)
  (for ([prog progs])
    (for ([input (input-names)])
      (define golden (golden-for prog input))
      (when golden
        (match (reference-output prog input)
          [(cons 'ok out) (check! 'interp prog input out golden)]
          [(cons 'error msg) (check! 'interp prog input (format "ERROR: ~a" msg) golden)])))))

;; ---------------------------------------------------------------------
;; chain mode: run the full frontend trace; every pass's interpreter
;; must agree with the golden, and every predicate must hold
;; ---------------------------------------------------------------------

(define (run-chain-tests progs)
  (for ([prog progs])
    (for ([input (input-names)])
      (define golden (golden-for prog input))
      (when golden
        (define p (read-program-file (program-path prog)))
        (define trace
          (with-handlers ([exn:fail? (λ (e) `(error ,(exn-message e)))])
            (run-chain p
                       (map first frontend-passes)
                       (map second frontend-passes)
                       (map third frontend-passes)
                       (map fourth frontend-passes)
                       (map fifth frontend-passes)
                       (input-ints input))))
        (match trace
          [`(error ,msg) (check! 'chain prog input (format "ERROR: ~a" msg) golden)]
          [_
           (for ([elt trace])
             #:break (hash-has-key? elt 'error)
             (define nm (hash-ref elt 'pass-name))
             #:final (equal? nm "uncover-locals")
             (unless (hash-ref elt 'satisfies-input-predicate)
               (check! (format "chain/~a/in-pred" nm) prog input "predicate FAILED" "predicate holds"))
             (unless (hash-ref elt 'satisfies-output-predicate)
               (check! (format "chain/~a/out-pred" nm) prog input "predicate FAILED" "predicate holds"))
             (check! (format "chain/~a" nm) prog input (hash-ref elt 'stdout "") golden))])))))

;; ---------------------------------------------------------------------
;; native modes
;; ---------------------------------------------------------------------

(define (run-native-tests progs tgt)
  (define exe (build-path (find-system-path 'temp-dir) (format "puffin-test-~a" tgt)))
  (for ([prog progs])
    (define compiled?
      (parameterize ([target tgt]
                     [write-stdout-mode #f]
                     [verbose-mode #f]
                     [executable-file (path->string exe)]
                     [asm-file (path->string (build-path (find-system-path 'temp-dir) "puffin-test.s"))]
                     [object-file (path->string (build-path (find-system-path 'temp-dir) "puffin-test.o"))])
        (with-handlers ([exn:fail? (λ (e)
                                     (check! (format "~a/compile" tgt) prog "-" (exn-message e) "compiles")
                                     #f)])
          (match (run/capture (λ () (run-assembler-linker (read-program-file (program-path prog)))))
            [(cons `(err ,_) out)
             (check! (format "~a/compile" tgt) prog "-" (string-append "compile error\n" out) "compiles")
             #f]
            [_ #t]))))
    (when compiled?
      (for ([input (input-names)])
        (define golden (golden-for prog input))
        (when golden
          (define-values (sp out in err)
            (subprocess #f #f #f exe))
          (fprintf in "~a\n" (string-join (map number->string (input-ints input)) " "))
          (close-output-port in)
          (define program-out (port->string out))
          (define err-out (port->string err))
          (subprocess-wait sp)
          (close-input-port out) (close-input-port err)
          (check! tgt prog input (string-append program-out err-out) golden))))))

;; ---------------------------------------------------------------------
;; entry
;; ---------------------------------------------------------------------

(define chosen-progs
  (command-line
   #:once-each
   [("-m" "--mode") m "Mode: interp | chain | x86-64 | arm64 | all | gen" (mode m)]
   #:args progs
   (if (empty? progs) (program-names) progs)))

;; ---------------------------------------------------------------------
;; puffincc mode: compile each program with the Puffin-written
;; compiler (build/puffincc; see bin/build-puffincc) and hold the
;; result to the same goldens
;; ---------------------------------------------------------------------

(define (run-puffincc-tests progs tgt)
  (define exe (build-path (find-system-path 'temp-dir) "puffincc-test"))
  (for ([prog progs])
    (define compiled?
      (match (run/capture
              (λ () (system (format "~a ~a ~a ~a"
                                    (build-path here 'up "bin" "puffincc-compile")
                                    (program-path prog) exe tgt))))
        [(cons #t _) #t]
        [(cons _ out)
         (check! 'puffincc/compile prog "-" (string-append "compile failed
" out) "compiles")
         #f]))
    (when compiled?
      (for ([input (input-names)])
        (define golden (golden-for prog input))
        (when golden
          (define-values (sp out in err) (subprocess #f #f #f exe))
          ;; a crashing binary may close stdin before we write it
          (with-handlers ([exn:fail? (lambda (_) (void))])
            (fprintf in "~a\n" (string-join (map number->string (input-ints input)) " "))
            (close-output-port in))
          (define program-out (port->string out))
          (define err-out (port->string err))
          (subprocess-wait sp)
          (close-input-port out) (close-input-port err)
          (check! 'puffincc prog input (string-append program-out err-out) golden))))))

(match (mode)
  [(or "gen") (generate-goldens chosen-progs)]
  ["interp" (run-interp-tests chosen-progs)]
  ["chain"  (run-chain-tests chosen-progs)]
  ["x86-64" (run-native-tests chosen-progs 'x86-64)]
  ["arm64"  (run-native-tests chosen-progs 'arm64)]
  ["puffincc" (run-puffincc-tests chosen-progs 'arm64)]
  ["puffincc-x86" (run-puffincc-tests chosen-progs 'x86-64)]
  ["all"
   (run-interp-tests chosen-progs)
   (run-native-tests chosen-progs 'x86-64)
   (when (equal? (default-target) 'arm64)
     (run-native-tests chosen-progs 'arm64))])

(unless (equal? (mode) "gen")
  (define fails (length (unbox failures)))
  (displayln (format "~a checks, ~a failures" (unbox n-checks) fails))
  (exit (if (zero? fails) 0 1)))
